Update images

diff --git a/images/solr/9.4/Dockerfile b/images/solr/9.4/Dockerfile
--- a/images/solr/9.4/Dockerfile
+++ b/images/solr/9.4/Dockerfile
@@ -1,6 +1,6 @@
 # syntax=docker/dockerfile:1
 # i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
-# © N.Harris Computer Corporation (2022-2023)
+# © N.Harris Computer Corporation (2022-2024)
 #
 # SPDX short identifier: MIT
 #
@@ -11,11 +11,11 @@ FROM eclipse-temurin:17-ubi9-minimal
 # Dynamic labels
 ARG revision
 
-ARG SOLR_VERSION="9.4.0"
+ARG SOLR_VERSION="9.4.1"
 # empty for the full distribution, "-slim" for the slim distribution
 ARG SOLR_DIST=""
-ARG SOLR_SHA512="7147caaec5290049b721f9a4e8b0c09b1775315fc4aa790fa7a88a783a45a61815b3532a938731fd583e91195492c4176f3c87d0438216dab26a07a4da51c1f5"
-ARG SOLR_KEYS="2289AC4180E130507D7A82F479C211E0AEFCA72E"
+ARG SOLR_SHA512="de22de737900e792776b35f598c14d734d432fdb9147feffd41694d66c521145c024f99ff180c2486ab91d96e34db34224f7cfa72b16afbe14d740c1d429a173"
+ARG SOLR_KEYS="515EA995ED1DD799FA1422E5CA7514D8385D790B"
 
 # Override the default solr download location with a preferred mirror, e.g.:
 #   docker build -t mine --build-arg SOLR_DOWNLOAD_SERVER=https://downloads.apache.org/solr/solr .
@@ -24,16 +24,24 @@ ARG SOLR_DOWNLOAD_SERVER="https://www.apache.org/dyn/closer.lua?action=download&
 
 RUN set -ex; \
   microdnf -y update; \
-  microdnf -y --setopt=install_weak_deps=0 install wget gpg gnupg dirmngr findutils; \
+  microdnf -y --setopt=install_weak_deps=0 install \
+    dirmngr \
+    findutils \
+    gnupg \
+    gpg \
+    openssl \
+    shadow-utils \
+    wget \
+  ; \
   rm -rf /var/lib/apt/lists/*; \
   export SOLR_BINARY="solr-$SOLR_VERSION$SOLR_DIST.tgz"; \
   MAX_REDIRECTS=3; \
   case "${SOLR_DOWNLOAD_SERVER}" in \
-  (*"apache.org"*);; \
-  (*) \
-  # If a non-ASF URL is provided, allow more redirects and skip GPG step.
-  MAX_REDIRECTS=4 && \
-  SKIP_GPG_CHECK=true;; \
+    (*"apache.org"*);; \
+    (*) \
+      # If a non-ASF URL is provided, allow more redirects and skip GPG step.
+      MAX_REDIRECTS=4 && \
+      SKIP_GPG_CHECK=true;; \
   esac; \
   export DOWNLOAD_URL="$SOLR_DOWNLOAD_SERVER/$SOLR_VERSION/$SOLR_BINARY"; \
   echo "downloading $DOWNLOAD_URL"; \
@@ -41,30 +49,30 @@ RUN set -ex; \
   if [ ! -f "/opt/$SOLR_BINARY" ]; then echo "failed download attempt for $SOLR_BINARY"; exit 1; fi; \
   echo "$SOLR_SHA512 */opt/$SOLR_BINARY" | sha512sum -c -; \
   if [ -z "$SKIP_GPG_CHECK" ]; then \
-  # Setup GPG \
-  export GNUPGHOME="/tmp/gnupg_home"; \
-  mkdir -p "$GNUPGHOME"; \
-  chmod 700 "$GNUPGHOME"; \
-  echo "disable-ipv6" >> "$GNUPGHOME/dirmngr.conf"; \
-  if [ -n "$SOLR_KEYS" ]; then \
-  # Install all Solr GPG Keys to start
-  wget -nv "https://downloads.apache.org/solr/KEYS" -O- | \
-  gpg --batch --import --key-origin 'url,https://downloads.apache.org/solr/KEYS'; \
-  # Save just the release key
-  release_keys="$(gpg --batch --export -a ${SOLR_KEYS})"; \
-  rm -rf "$GNUPGHOME"/*; \
-  echo "${release_keys}" | gpg --batch --import; \
-  fi; \
-  # Do GPG Checks
-  echo "downloading $DOWNLOAD_URL.asc"; \
-  wget -nv "$DOWNLOAD_URL.asc" -O "/opt/$SOLR_BINARY.asc"; \
-  (>&2 ls -l "/opt/$SOLR_BINARY" "/opt/$SOLR_BINARY.asc"); \
-  gpg --batch --verify "/opt/$SOLR_BINARY.asc" "/opt/$SOLR_BINARY"; \
-  # Cleanup GPG
-  { command -v gpgconf; gpgconf --kill all || :; }; \
-  rm -r "$GNUPGHOME"; \
+    # Setup GPG \
+    export GNUPGHOME="/tmp/gnupg_home"; \
+    mkdir -p "$GNUPGHOME"; \
+    chmod 700 "$GNUPGHOME"; \
+    echo "disable-ipv6" >> "$GNUPGHOME/dirmngr.conf"; \
+    if [ -n "$SOLR_KEYS" ]; then \
+      # Install all Solr GPG Keys to start
+      wget -nv "https://downloads.apache.org/solr/KEYS" -O- | \
+        gpg --batch --import --key-origin 'url,https://downloads.apache.org/solr/KEYS'; \
+      # Save just the release key
+      release_keys="$(gpg --batch --export -a ${SOLR_KEYS})"; \
+      rm -rf "$GNUPGHOME"/*; \
+      echo "${release_keys}" | gpg --batch --import; \
+    fi; \
+    # Do GPG Checks
+    echo "downloading $DOWNLOAD_URL.asc"; \
+    wget -nv "$DOWNLOAD_URL.asc" -O "/opt/$SOLR_BINARY.asc"; \
+    (>&2 ls -l "/opt/$SOLR_BINARY" "/opt/$SOLR_BINARY.asc"); \
+    gpg --batch --verify "/opt/$SOLR_BINARY.asc" "/opt/$SOLR_BINARY"; \
+    # Cleanup GPG
+    { command -v gpgconf; gpgconf --kill all || :; }; \
+    rm -r "$GNUPGHOME"; \
   else \
-  echo "Skipping GPG validation due to non-Apache build"; \
+    echo "Skipping GPG validation due to non-Apache build"; \
   fi; \
   tar -C /opt --extract --preserve-permissions --file "/opt/$SOLR_BINARY"; \
   rm "/opt/$SOLR_BINARY"*; \
@@ -75,12 +83,13 @@ LABEL name="Apache Solr" \
   version="${SOLR_VERSION}" \
   revision="${revision}" \
   summary="Apache Solr image based on Red Hat ubi." \
-  description="Solr is the popular, blazing fast, open source NoSQL search platform from the Apache Lucene project." \
+  description="Solr is the popular, blazing fast, open source search platform from the Apache Lucene project." \
   license="MIT"
 
 # The Java Security Manager is disabled since it is being deprecated and subject to removal in a future release.
 # https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/SecurityManager.html
 ENV JAVA_HOME="/opt/java/openjdk" \
+  SOLR_SECURITY_MANAGER_ENABLED="false" \
   SOLR_USER="solr" \
   SOLR_UID="8983" \
   SOLR_GROUP="solr" \
@@ -92,8 +101,7 @@ ENV JAVA_HOME="/opt/java/openjdk" \
   SOLR_LOGS_DIR=/var/solr/logs \
   LOG4J_PROPS=/var/solr/log4j2.xml \
   SOLR_JETTY_HOST="0.0.0.0" \
-  SOLR_SECURITY_MANAGER_ENABLED="false"
-
+  SOLR_ZK_EMBEDDED_HOST="0.0.0.0"
 
 RUN set -ex; \
   groupadd -r --gid "$SOLR_GID" "$SOLR_GROUP"; \
@@ -112,6 +120,7 @@ RUN set -ex; \
   mv /opt/solr/bin/solr.in.cmd /opt/solr/bin/solr.in.cmd.orig; \
   chmod 0664 /etc/default/solr.in.sh; \
   mkdir -p -m0770 /var/solr; \
+  # Official code only chown's /var/solr but we need more /opt/solr/server/resources /opt/solr/example too.
   chown -R "$SOLR_USER:0" /var/solr /opt/solr/server/resources /opt/solr/example; \
   test ! -e /opt/solr/modules || ln -s /opt/solr/modules /opt/solr/contrib; \
   test ! -e /opt/solr/prometheus-exporter || ln -s /opt/solr/prometheus-exporter /opt/solr/modules/prometheus-exporter;
@@ -124,16 +133,23 @@ ARG GOSU_VERSION=1.17
 RUN set -ex; \
   ARCH="$(uname -m)"; \
   if [ "${ARCH}" != "aarch64" ]; then \
-  wget -nv "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64" -O /usr/local/bin/gosu; \
-  else wget -nv "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-arm64" -O /usr/local/bin/gosu; fi; \
+    wget -nv "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64" -O /usr/local/bin/gosu; \
+  else \
+    wget -nv "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-arm64" -O /usr/local/bin/gosu; \
+  fi; \
   chmod +x /usr/local/bin/gosu; \
   # Verify that the binary works
   gosu nobody true; \
-  cd /usr/local/bin; wget -nv https://github.com/apangin/jattach/releases/download/v2.1/jattach; chmod 755 jattach; \
-  echo >jattach.sha512 "b6643d00d8749aefbd56d7ca1434951916e02622526bd419fd0aa7cdfe8ba9fd99417474b50fbc7faab75f45457f3364a0bc45b886734ef3e04f88c2a203304b  jattach"; \
+  cd /usr/local/bin; wget -nv https://github.com/apangin/jattach/releases/download/v2.2/jattach; chmod 755 jattach; \
+  echo >jattach.sha512 "53a5d9b49875bc4437ac5b20440e48c66fa42df4aa42c3e50b03a3e5937a855a071a4e65c53b304a47c11353f817feac47ef6d7d86bd9641dc11d2e7d0af6a7a  jattach"; \
   sha512sum -c jattach.sha512; rm jattach.sha512; \
   microdnf -y update; \
-  microdnf -y --setopt=install_weak_deps=0 install acl lsof procps wget nmap; \
+  microdnf -y --setopt=install_weak_deps=0 install \
+    acl \
+    lsof \
+    procps \
+    nmap \
+    ; \
   microdnf clean all;
 
 VOLUME /var/solr
