Update images

diff --git a/images/analyze-containers-base/ubi-jdk17/Dockerfile b/images/analyze-containers-base/ubi-jdk17/Dockerfile
--- a/images/analyze-containers-base/ubi-jdk17/Dockerfile
+++ b/images/analyze-containers-base/ubi-jdk17/Dockerfile
@@ -10,40 +10,93 @@ ARG revision
 # version = image version = name of the directory this Dockerfile is in
 ARG version
 
-# Stage 1: Build xmlstarlet from source
-FROM registry.access.redhat.com/ubi9/ubi as builder
 
+
+# Stage 1: Download everything we need
+# Use ubuntu, because we can't untar on ubi reliably on arm64.
+# (on arm64, tar reports a lot of "Cannot open: Invalid argument" errors)
+FROM ubuntu:24.04 as downloader-and-unpacker
+
+ARG GOSU_VERSION="1.19"
 ARG XMLSTARLET_VERSION="1.6.1"
 
+RUN apt-get update && \
+    apt-get install --no-install-recommends -y \
+      ca-certificates \
+      wget \
+    && \
+    rm -rf /var/lib/apt/lists/*
+
+# GOSU binary can be downloaded directly
+RUN set -eux; \
+    TARGET_DIR='/gosu' && \
+    ARCH="$(uname -m)" && \
+    mkdir -p "${TARGET_DIR}" && \
+    if [ "${ARCH}" != "aarch64" ] && [ "${ARCH}" != "arm64" ]; then \
+      DOWNLOAD_URL="https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64"; \
+    else \
+      DOWNLOAD_URL="https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-arm64"; \
+    fi && \
+    wget --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --retry-connrefused "${DOWNLOAD_URL}" -O "${TARGET_DIR}/gosu" && \
+    chmod 0755 "${TARGET_DIR}/gosu" && \
+    "${TARGET_DIR}/gosu" nobody true
+
+RUN set -eux; \
+    TARGET_DIR='/xmlstarlet'; \
+    DOWNLOADED_TAR_FILE='/tmp/xmlstarlet.tar.gz'; \
+    DOWNLOAD_URL="https://sourceforge.net/projects/xmlstar/files/xmlstarlet/${XMLSTARLET_VERSION}/xmlstarlet-${XMLSTARLET_VERSION}.tar.gz"; \
+    mkdir -p "${TARGET_DIR}" && \
+    wget --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --retry-connrefused "${DOWNLOAD_URL}" -O "${DOWNLOADED_TAR_FILE}" && \
+    ls -al "${DOWNLOADED_TAR_FILE}" && \
+    tar -tzf "${DOWNLOADED_TAR_FILE}" && \
+    cd "${TARGET_DIR}" && \
+    if tar -xzf "${DOWNLOADED_TAR_FILE}" --strip-components=1 --verbose; then \
+      rm -f "${DOWNLOADED_TAR_FILE}" ; \
+    else \
+      echo "Tar extraction failed. Extracted contents was:" >&2; \
+      find "${TARGET_DIR}" -ls >&2; \
+      exit 1; \
+    fi
+
+
+
+# Stage 2: Build xmlstarlet from source on the OS of the final image so libraries match.
+FROM eclipse-temurin:17-ubi9-minimal as builder
+
 # Install required dependencies
-RUN dnf update -y; \
-    dnf install -y \
-    gcc \
-    gcc-c++ \
-    make \
-    libxml2-devel \
-    libxslt-devel \
-    wget \
-    && dnf clean all
+RUN microdnf -y update && \
+    microdnf -y install \
+      gcc \
+      gcc-c++ \
+      make \
+      libxml2-devel \
+      libxslt-devel \
+    && \
+    microdnf clean all
 
 # Set the include path for libxml2 headers
 ENV CFLAGS="-I/usr/include/libxml2"
 
-# Download, extract and compile xmlstarlet source code
-RUN wget --progress=dot:giga "https://sourceforge.net/projects/xmlstar/files/xmlstarlet/${XMLSTARLET_VERSION}/xmlstarlet-${XMLSTARLET_VERSION}.tar.gz" -O "/opt/xmlstarlet-${XMLSTARLET_VERSION}.tar.gz"; \
-    tar -xzf "/opt/xmlstarlet-${XMLSTARLET_VERSION}.tar.gz" -C "/opt"; \
-    cd "/opt/xmlstarlet-${XMLSTARLET_VERSION}" || exit; \
-    ./configure && make -s; \
-    mv "/opt/xmlstarlet-${XMLSTARLET_VERSION}/xml" "/opt/xmlstarlet"
+# Grab xmlstarlet source code from the downloader-and-unpacker stage
+COPY --from=downloader-and-unpacker /xmlstarlet /root/xmlstarlet
+# Compile xmlstarlet from the source code we just grabbed
+RUN set -eux; \
+    cd '/root/xmlstarlet' && \
+    TARGET_FILE='/opt/xmlstarlet' && \
+    find . -ls && \
+    ./configure && make -s && \
+    mv 'xml' "${TARGET_FILE}" && \
+    chmod 0755 "${TARGET_FILE}" && \
+    ls -al "${TARGET_FILE}"
 
-# Stage 2: Create the final image
+
+
+# Stage 3: Create the final image
 FROM eclipse-temurin:17-ubi9-minimal
 
 # Bring global-scope args into the build stage
 ARG revision
 ARG version
-
-SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
 LABEL name="Analyze Containers Base" \
   version="${version}" \
@@ -53,7 +106,7 @@ LABEL name="Analyze Containers Base" \
   description="This image contains OpenJDK 17 Eclipse Temurin runtime and Red Hat's UBI as the base OS." \
   license="MIT"
 
-ARG GOSU_VERSION=1.17
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
 # Use root but change at runtime with GOSU
 # hadolint ignore=DL3002
@@ -61,31 +114,26 @@ USER root
 
 # Install shared packages
 RUN set -eux; \
-  microdnf -y update; \
+  microdnf -y update && \
   microdnf -y install \
-  jq \
-  iputils \
-  shadow-utils \
-  diffutils \
-  findutils \
-  tar \
-  gzip \
-  ca-certificates \
-  gnupg \
-  rsync \
-  openssl \
-  libxml2 \
-  libxslt; \
+    jq \
+    iputils \
+    shadow-utils \
+    diffutils \
+    findutils \
+    tar \
+    gzip \
+    ca-certificates \
+    gnupg \
+    rsync \
+    openssl \
+    libxml2 \
+    libxslt \
+  && \
   microdnf clean all;
 
 # Copy the compiled xmlstarlet binary from the builder stage
 COPY --from=builder /opt/xmlstarlet /usr/local/bin/xmlstarlet
 
-# GOSU layer
-RUN ARCH="$(uname -m)"; \
-  if [ "${ARCH}" != "aarch64" ] && [ "${ARCH}" != "arm64" ]; then \
-  curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64"; \
-  else curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-arm64"; fi; \
-  chmod +x /usr/local/bin/gosu; \
-  # Verify that the binary works
-  gosu nobody true;
+# Copy the gosu binary from the downloader-and-unpacker stage
+COPY --from=downloader-and-unpacker /gosu/gosu /usr/local/bin/gosu
diff --git a/images/solr/8.11/Dockerfile b/images/solr/8.11/Dockerfile
--- a/images/solr/8.11/Dockerfile
+++ b/images/solr/8.11/Dockerfile
@@ -4,7 +4,7 @@
 #
 # SPDX short identifier: MIT
 #
-# Inspired by: https://github.com/apache/solr-docker
+# Inspired by: https://github.com/apache/solr-docker/blob/aa51c522c3e74cd1b2886209ea249358a34d324a/8.11/Dockerfile
 
 # Dynamic labels passed at build time into global-scope
 # revision = CI build number or 'dev' for local builds
@@ -12,23 +12,128 @@ ARG revision
 # version = image version = name of the directory this Dockerfile is in
 ARG version
 
-FROM eclipse-temurin:11-ubi9-minimal
-
-# Bring global-scope args into the build stage
-ARG revision
-ARG version
-
-SHELL ["/bin/bash", "-o", "pipefail", "-c"]
-
 ARG SOLR_VERSION="8.11.4"
 ARG SOLR_SHA512="828a7c3c06f3ccca852f2c3f91d72bf032cf102646283f4e603bbc3c3f3753978ce8b5c014c4263fb66c251b6726105956ad726baee63af6568637eba0416612"
 ARG SOLR_KEYS="50E3EE1C91C7E0CB4DFB007B369424FC98F3F6EC"
 # If specified, this will override SOLR_DOWNLOAD_SERVER and all ASF mirrors. Typically used downstream for custom builds
 ARG SOLR_DOWNLOAD_URL
-
 # Override the solr download location with e.g.:
 #   docker build -t mine --build-arg SOLR_DOWNLOAD_SERVER=http://www-eu.apache.org/dist/lucene/solr .
 ARG SOLR_DOWNLOAD_SERVER="https://www.apache.org/dyn/closer.lua?action=download&filename=/solr/solr"
+ARG JATTACH_URL="https://github.com/apangin/jattach/releases/download/v2.0/jattach"
+ARG JATTACH_SHA512="a19e774600d6aa844bceb2189285848127a70130a69fb1840c10367f3360972c733b3f09e60e9672d387e2d48c750ab56acfe8f80f7c6af76f5d1123e5ad7222"
+
+
+
+# Stage 1: Download everything we need
+# Use ubuntu, because we can't untar on ubi reliably on arm64.
+# (on arm64, tar reports a lot of "Cannot open: Invalid argument" errors)
+FROM ubuntu:24.04 as downloader-and-unpacker
+
+# Bring global-scope args into the build stage, and add more
+ARG SOLR_VERSION
+ARG SOLR_SHA512
+ARG SOLR_KEYS
+ARG SOLR_DOWNLOAD_URL
+ARG SOLR_DOWNLOAD_SERVER
+ARG JATTACH_URL
+ARG JATTACH_SHA512
+ENV \
+    SOLR_CLOSER_URL="http://www.apache.org/dyn/closer.lua?filename=lucene/solr/$SOLR_VERSION/solr-$SOLR_VERSION.tgz&action=download" \
+    SOLR_DIST_URL="https://www.apache.org/dist/lucene/solr/$SOLR_VERSION/solr-$SOLR_VERSION.tgz" \
+    SOLR_ARCHIVE_URL="https://archive.apache.org/dist/lucene/solr/$SOLR_VERSION/solr-$SOLR_VERSION.tgz"
+
+# Dependencies for downloading and verifying Solr.
+# Subset of those used in the official Solr image.
+RUN apt-get update && \
+    apt-get install --no-install-recommends -y \
+      ca-certificates \
+      dirmngr \
+      gnupg \
+      wget \
+    && \
+    rm -rf /var/lib/apt/lists/*
+
+# Download jattach and put it into /jattach for easy copying later.
+RUN set -ex; \
+  mkdir /jattach && \
+  cd /jattach && \
+  wget --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --retry-connrefused "${JATTACH_URL}" -O jattach && \
+  chmod 755 jattach && \
+  echo "${JATTACH_SHA512}  jattach" >jattach.sha512 && \
+  sha512sum -c jattach.sha512 && \
+  rm jattach.sha512 && \
+  ls -al /jattach
+
+# Download, verify, and extract Solr
+# Code from official image's Dockerfile...
+RUN set -ex; \
+  export GNUPGHOME="/tmp/gnupg_home"; \
+  mkdir -p "$GNUPGHOME"; \
+  chmod 700 "$GNUPGHOME"; \
+  echo "disable-ipv6" >> "$GNUPGHOME/dirmngr.conf"; \
+  for key in $SOLR_KEYS; do \
+    found=''; \
+    for server in \
+      ha.pool.sks-keyservers.net \
+      hkp://keyserver.ubuntu.com:80 \
+      hkp://p80.pool.sks-keyservers.net:80 \
+      pgp.mit.edu \
+    ; do \
+      echo "  trying $server for $key"; \
+      gpg --batch --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$key" && found=yes && break; \
+      gpg --batch --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$key" && found=yes && break; \
+    done; \
+    test -z "$found" && echo >&2 "error: failed to fetch $key from several disparate servers -- network issues?" && exit 1; \
+  done; \
+  exit 0
+
+# Code from official image's Dockerfile...
+# ... truncated after the 'tar' step, with the 'tar' going into '/solr' instead of '/opt/'
+# ... with wget told --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --retry-connrefused for robustness.
+RUN set -ex; \
+  export GNUPGHOME="/tmp/gnupg_home"; \
+  MAX_REDIRECTS=1; \
+  if [ -n "$SOLR_DOWNLOAD_URL" ]; then \
+    # If a custom URL is defined, we download from non-ASF mirror URL and allow more redirects and skip GPG step
+    # This takes effect only if the SOLR_DOWNLOAD_URL build-arg is specified, typically in downstream Dockerfiles
+    MAX_REDIRECTS=4; \
+    SKIP_GPG_CHECK=true; \
+  elif [ -n "$SOLR_DOWNLOAD_SERVER" ]; then \
+    SOLR_DOWNLOAD_URL="$SOLR_DOWNLOAD_SERVER/$SOLR_VERSION/solr-$SOLR_VERSION.tgz"; \
+  fi; \
+  for url in $SOLR_DOWNLOAD_URL $SOLR_CLOSER_URL $SOLR_DIST_URL $SOLR_ARCHIVE_URL; do \
+    if [ -f "/opt/solr-$SOLR_VERSION.tgz" ]; then break; fi; \
+    echo "downloading $url"; \
+    if wget --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --max-redirect $MAX_REDIRECTS --retry-connrefused "$url" -O "/opt/solr-$SOLR_VERSION.tgz"; then break; else rm -f "/opt/solr-$SOLR_VERSION.tgz"; fi; \
+  done; \
+  if [ ! -f "/opt/solr-$SOLR_VERSION.tgz" ]; then echo "failed all download attempts for solr-$SOLR_VERSION.tgz"; exit 1; fi; \
+  if [ -z "$SKIP_GPG_CHECK" ]; then \
+    echo "downloading $SOLR_ARCHIVE_URL.asc"; \
+    wget --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --retry-connrefused "$SOLR_ARCHIVE_URL.asc" -O "/opt/solr-$SOLR_VERSION.tgz.asc"; \
+    echo "$SOLR_SHA512 */opt/solr-$SOLR_VERSION.tgz" | sha512sum -c -; \
+    (>&2 ls -l "/opt/solr-$SOLR_VERSION.tgz" "/opt/solr-$SOLR_VERSION.tgz.asc"); \
+    gpg --batch --verify "/opt/solr-$SOLR_VERSION.tgz.asc" "/opt/solr-$SOLR_VERSION.tgz"; \
+  else \
+    echo "Skipping GPG validation due to non-Apache build"; \
+  fi; \
+  mkdir -p /solr && \
+  tar -C /solr --extract --file "/opt/solr-$SOLR_VERSION.tgz" && \
+  { command -v gpgconf; gpgconf --kill all || :; } && \
+  rm -rf "$GNUPGHOME" "/opt/solr-$SOLR_VERSION.tgz" "/opt/solr-$SOLR_VERSION.tgz.asc" && \
+  ls -al /solr
+
+
+
+# Stage 2: Create the final image
+FROM eclipse-temurin:11-ubi9-minimal
+
+# Bring global-scope args into the build stage
+ARG revision
+ARG version
+ARG SOLR_VERSION
+
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
 LABEL name="Apache Solr" \
   maintainer="i2 Group" \
@@ -38,84 +143,51 @@ LABEL name="Apache Solr" \
   description="Solr is the popular, blazing fast, open source NoSQL search platform from the Apache Lucene project." \
   license="MIT"
 
-RUN set -ex; \
-  microdnf -y install acl shadow-utils dirmngr gpg lsof procps wget openssl tar gzip findutils; \
-  microdnf clean all; \
-  cd /usr/local/bin; wget -nv https://github.com/apangin/jattach/releases/download/v2.0/jattach; chmod 755 jattach; \
-  echo >jattach.sha512 "a19e774600d6aa844bceb2189285848127a70130a69fb1840c10367f3360972c733b3f09e60e9672d387e2d48c750ab56acfe8f80f7c6af76f5d1123e5ad7222  jattach"; \
-  sha512sum -c jattach.sha512; rm jattach.sha512
+RUN set -eux; \
+    microdnf -y install \
+      acl \
+      lsof \
+      procps \
+      openssl \
+      gzip \
+      findutils \
+    && \
+    microdnf clean all
 
+# Copy jattach from the downloader-and-unpacker stage.
+# Original Dockerfile downloaded it as part of the previous RUN step.
+COPY --from=downloader-and-unpacker /jattach/jattach /usr/local/bin/jattach
+
+# Original Dockerfile set all these ... but we had to move the SOLR_..._URL args up to the downloader stage
 ENV JAVA_HOME="/opt/java/openjdk" \
-  PATH="/opt/solr/bin:/opt/docker-solr/scripts:/opt/java/openjdk/bin:$PATH" \
-  SOLR_USER="solr" \
-  SOLR_UID="8983" \
-  SOLR_GROUP="solr" \
-  SOLR_GID="8983" \
-  SOLR_CLOSER_URL="http://www.apache.org/dyn/closer.lua?filename=lucene/solr/$SOLR_VERSION/solr-$SOLR_VERSION.tgz&action=download" \
-  SOLR_DIST_URL="https://www.apache.org/dist/lucene/solr/$SOLR_VERSION/solr-$SOLR_VERSION.tgz" \
-  SOLR_ARCHIVE_URL="https://archive.apache.org/dist/lucene/solr/$SOLR_VERSION/solr-$SOLR_VERSION.tgz" \
-  SOLR_INCLUDE=/etc/default/solr.in.sh \
-  SOLR_HOME=/var/solr/data \
-  SOLR_BACKUP=$SOLR_BACKUP_DIR \
-  SOLR_PID_DIR=/var/solr \
-  SOLR_LOGS_DIR=/var/solr/logs \
-  LOG4J_PROPS=/var/solr/log4j2.xml
+    PATH="/opt/solr/bin:/opt/docker-solr/scripts:/opt/java/openjdk/bin:$PATH" \
+    SOLR_USER="solr" \
+    SOLR_UID="8983" \
+    SOLR_GROUP="solr" \
+    SOLR_GID="8983" \
+    SOLR_INCLUDE=/etc/default/solr.in.sh \
+    SOLR_HOME=/var/solr/data \
+    SOLR_BACKUP=$SOLR_BACKUP_DIR \
+    SOLR_PID_DIR=/var/solr \
+    SOLR_LOGS_DIR=/var/solr/logs \
+    LOG4J_PROPS=/var/solr/log4j2.xml
 
-RUN set -ex; \
-  groupadd -r --gid "$SOLR_GID" "$SOLR_GROUP"; \
-  useradd -r --uid "$SOLR_UID" --gid "$SOLR_GID" "$SOLR_USER"
+# Install shadow-utils temporarily, use it, then remove it to keep image small
+RUN set -eux; \
+    microdnf -y install shadow-utils && \
+    groupadd -r --gid "$SOLR_GID" "$SOLR_GROUP" && \
+    useradd -r --uid "$SOLR_UID" --gid "$SOLR_GID" "$SOLR_USER" && \
+    microdnf -y remove shadow-utils && \
+    microdnf clean all
 
-RUN set -ex; \
-  export GNUPGHOME="/tmp/gnupg_home"; \
-  mkdir -p "$GNUPGHOME"; \
-  chmod 700 "$GNUPGHOME"; \
-  echo "disable-ipv6" >> "$GNUPGHOME/dirmngr.conf"; \
-  for key in $SOLR_KEYS; do \
-  found=''; \
-  for server in \
-  ha.pool.sks-keyservers.net \
-  hkp://keyserver.ubuntu.com:80 \
-  hkp://p80.pool.sks-keyservers.net:80 \
-  pgp.mit.edu \
-  ; do \
-  echo "  trying $server for $key"; \
-  gpg --batch --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$key" && found=yes && break; \
-  gpg --batch --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$key" && found=yes && break; \
-  done; \
-  test -z "$found" && echo >&2 "error: failed to fetch $key from several disparate servers -- network issues?" && exit 1; \
-  done; \
-  exit 0
-
-RUN set -ex; \
-  export GNUPGHOME="/tmp/gnupg_home"; \
-  MAX_REDIRECTS=1; \
-  if [ -n "$SOLR_DOWNLOAD_URL" ]; then \
-  # If a custom URL is defined, we download from non-ASF mirror URL and allow more redirects and skip GPG step
-  # This takes effect only if the SOLR_DOWNLOAD_URL build-arg is specified, typically in downstream Dockerfiles
-  MAX_REDIRECTS=4; \
-  SKIP_GPG_CHECK=true; \
-  elif [ -n "$SOLR_DOWNLOAD_SERVER" ]; then \
-  SOLR_DOWNLOAD_URL="$SOLR_DOWNLOAD_SERVER/$SOLR_VERSION/solr-$SOLR_VERSION.tgz"; \
-  fi; \
-  for url in $SOLR_DOWNLOAD_URL $SOLR_CLOSER_URL $SOLR_DIST_URL $SOLR_ARCHIVE_URL; do \
-  if [ -f "/opt/solr-$SOLR_VERSION.tgz" ]; then break; fi; \
-  echo "downloading $url"; \
-  # Change to verbose to debug why we are hanging on download
-  if wget -t 10 --max-redirect $MAX_REDIRECTS --retry-connrefused -v "$url" -O "/opt/solr-$SOLR_VERSION.tgz"; then break; else rm -f "/opt/solr-$SOLR_VERSION.tgz"; fi; \
-  done; \
-  if [ ! -f "/opt/solr-$SOLR_VERSION.tgz" ]; then echo "failed all download attempts for solr-$SOLR_VERSION.tgz"; exit 1; fi; \
-    if [ -z "$SKIP_GPG_CHECK" ]; then \
-  echo "downloading $SOLR_ARCHIVE_URL.asc"; \
-  wget -nv "$SOLR_ARCHIVE_URL.asc" -O "/opt/solr-$SOLR_VERSION.tgz.asc"; \
-echo "$SOLR_SHA512 */opt/solr-$SOLR_VERSION.tgz" | sha512sum -c -; \
-  (>&2 ls -l "/opt/solr-$SOLR_VERSION.tgz" "/opt/solr-$SOLR_VERSION.tgz.asc"); \
-  gpg --batch --verify "/opt/solr-$SOLR_VERSION.tgz.asc" "/opt/solr-$SOLR_VERSION.tgz"; \
-  else \
-  echo "Skipping GPG validation due to non-Apache build"; \
-  fi; \
-  tar -C /opt --extract --file "/opt/solr-$SOLR_VERSION.tgz"; \
+# Copy solr directory tree from the downloader-and-unpacker stage.
+# Original Dockerfile had a RUN step we've had to split at the tar step.
+COPY --from=downloader-and-unpacker /solr /opt/
+# ... and then continue with the rest of the original RUN step after the tar step
+# ... except for some tidy-up that we did earlier.
+RUN set -eux; \
+  ls -al /opt/; \
   (cd /opt; ln -s "solr-$SOLR_VERSION" solr); \
-  rm "/opt/solr-$SOLR_VERSION.tgz"*; \
   rm -Rf /opt/solr/docs/ /opt/solr/dist/{solr-core-$SOLR_VERSION.jar,solr-solrj-$SOLR_VERSION.jar,solrj-lib,solr-test-framework-$SOLR_VERSION.jar,test-framework}; \
   mkdir -p /opt/solr/server/solr/lib /docker-entrypoint-initdb.d /opt/docker-solr; \
   chown -R 0:0 "/opt/solr-$SOLR_VERSION"; \
@@ -136,9 +208,7 @@ echo "$SOLR_SHA512 */opt/solr-$SOLR_VERSION.tgz" | sha512sum -c -; \
   sed -i -e 's/lsof -PniTCP:/lsof -t -PniTCP:/' /opt/solr/bin/solr; \
   chown -R "0:0" /opt/solr-$SOLR_VERSION /docker-entrypoint-initdb.d /opt/docker-solr; \
   chown -R "$SOLR_USER:0" /var/solr /opt/solr/example; \
-  chown "$SOLR_USER:0" /opt/solr/server/resources/log4j2-console.xml; \
-  { command -v gpgconf; gpgconf --kill all || :; }; \
-  rm -r "$GNUPGHOME"
+  chown "$SOLR_USER:0" /opt/solr/server/resources/log4j2-console.xml
 
 COPY --chown=0:0 scripts /opt/docker-solr/scripts
 
diff --git a/images/solr/9.9/Dockerfile b/images/solr/9.9/Dockerfile
--- a/images/solr/9.9/Dockerfile
+++ b/images/solr/9.9/Dockerfile
@@ -12,12 +12,6 @@ ARG revision
 # version = image version = name of the directory this Dockerfile is in
 ARG version
 
-FROM i2group/i2eng-analyze-containers-base:ubi-jdk17-${revision}
-
-# Bring global-scope args into the build stage
-ARG revision
-ARG version
-
 ARG SOLR_VERSION="9.9.0"
 # empty for the full distribution, "-slim" for the slim distribution
 ARG SOLR_DIST=""
@@ -28,11 +22,51 @@ ARG SOLR_KEYS="50E3EE1C91C7E0CB4DFB007B369424FC98F3F6EC"
 #   docker build -t mine --build-arg SOLR_DOWNLOAD_SERVER=https://downloads.apache.org/solr/solr .
 # This server must support downloading at: ${SOLR_DOWNLOAD_SERVER}/${SOLR_VERSION}/solr-${SOLR_VERSION}(-slim).tgz(.asc)
 ARG SOLR_DOWNLOAD_SERVER="https://www.apache.org/dyn/closer.lua?action=download&filename=/solr/solr"
+ARG JATTACH_URL="https://github.com/jattach/jattach/releases/download/v2.2/jattach"
+ARG JATTACH_SHA512="53a5d9b49875bc4437ac5b20440e48c66fa42df4aa42c3e50b03a3e5937a855a071a4e65c53b304a47c11353f817feac47ef6d7d86bd9641dc11d2e7d0af6a7a"
 
+
+
+# Stage 1: Download everything we need
+# Use ubuntu, because we can't untar on ubi reliably on arm64.
+# (on arm64, tar reports a lot of "Cannot open: Invalid argument" errors)
+FROM ubuntu:24.04 as downloader-and-unpacker
+
+# Bring global-scope args into the build stage
+ARG SOLR_VERSION
+ARG SOLR_DIST
+ARG SOLR_SHA512
+ARG SOLR_KEYS
+ARG SOLR_DOWNLOAD_SERVER
+ARG JATTACH_URL
+ARG JATTACH_SHA512
+
+# Dependencies for downloading and verifying Solr.
+# Subset of those used in the official Solr image.
+RUN apt-get update && \
+    apt-get install --no-install-recommends -y \
+      ca-certificates \
+      dirmngr \
+      gnupg \
+      wget \
+    && \
+    rm -rf /var/lib/apt/lists/*
+
+# Download jattach and put it into /jattach for easy copying later.
 RUN set -ex; \
-  microdnf -y update; \
-  microdnf -y --setopt=install_weak_deps=0 install wget gpg gnupg dirmngr; \
-  rm -rf /var/lib/apt/lists/*; \
+  mkdir /jattach && \
+  cd /jattach && \
+  wget --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --retry-connrefused "${JATTACH_URL}" -O jattach && \
+  chmod 755 jattach && \
+  echo "${JATTACH_SHA512}  jattach" >jattach.sha512 && \
+  sha512sum -c jattach.sha512 && \
+  rm jattach.sha512
+
+# Download, verify, and extract Solr
+# Code from official image's Dockerfile...
+# ... truncated after the 'tar' step, with the 'tar' going into '/solr' instead of '/opt/'
+# ... with wget told --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --retry-connrefused for robustness.
+RUN set -ex; \
   export SOLR_BINARY="solr-$SOLR_VERSION$SOLR_DIST.tgz"; \
   MAX_REDIRECTS=3; \
   case "${SOLR_DOWNLOAD_SERVER}" in \
@@ -44,8 +78,7 @@ RUN set -ex; \
   esac; \
   export DOWNLOAD_URL="$SOLR_DOWNLOAD_SERVER/$SOLR_VERSION/$SOLR_BINARY"; \
   echo "downloading $DOWNLOAD_URL"; \
-  # Change to verbose to debug why we are hanging on download
-  if ! wget -t 10 --max-redirect $MAX_REDIRECTS --retry-connrefused -v "$DOWNLOAD_URL" -O "/opt/$SOLR_BINARY"; then rm -f "/opt/$SOLR_BINARY"; fi; \
+  if ! wget --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --max-redirect $MAX_REDIRECTS --retry-connrefused "$DOWNLOAD_URL" -O "/opt/$SOLR_BINARY"; then rm -f "/opt/$SOLR_BINARY"; fi; \
   if [ ! -f "/opt/$SOLR_BINARY" ]; then echo "failed download attempt for $SOLR_BINARY"; exit 1; fi; \
   echo "$SOLR_SHA512 */opt/$SOLR_BINARY" | sha512sum -c -; \
   if [ -z "$SKIP_GPG_CHECK" ]; then \
@@ -56,7 +89,7 @@ RUN set -ex; \
     echo "disable-ipv6" >> "$GNUPGHOME/dirmngr.conf"; \
     if [ -n "$SOLR_KEYS" ]; then \
       # Install all Solr GPG Keys to start
-      wget -nv "https://downloads.apache.org/solr/KEYS" -O- | \
+      wget --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --retry-connrefused "https://downloads.apache.org/solr/KEYS" -O- | \
         gpg --batch --import --key-origin 'url,https://downloads.apache.org/solr/KEYS'; \
       # Save just the release key
       release_keys="$(gpg --batch --export -a ${SOLR_KEYS})"; \
@@ -65,7 +98,7 @@ RUN set -ex; \
     fi; \
     # Do GPG Checks
     echo "downloading $DOWNLOAD_URL.asc"; \
-    wget -nv "$DOWNLOAD_URL.asc" -O "/opt/$SOLR_BINARY.asc"; \
+    wget --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --retry-connrefused "$DOWNLOAD_URL.asc" -O "/opt/$SOLR_BINARY.asc"; \
     (>&2 ls -l "/opt/$SOLR_BINARY" "/opt/$SOLR_BINARY.asc"); \
     gpg --batch --verify "/opt/$SOLR_BINARY.asc" "/opt/$SOLR_BINARY"; \
     # Cleanup GPG
@@ -75,8 +108,17 @@ RUN set -ex; \
     echo "Skipping GPG validation due to non-Apache build"; \
   fi; \
   tar -C /opt --extract --preserve-permissions --file "/opt/$SOLR_BINARY"; \
-  rm "/opt/$SOLR_BINARY"*; \
-  microdnf clean all;
+  rm "/opt/$SOLR_BINARY"*
+
+
+
+# Stage 2: Create the final image
+FROM i2group/i2eng-analyze-containers-base:ubi-jdk17-${revision}
+
+# Bring global-scope args into the build stage
+ARG revision
+ARG version
+ARG SOLR_VERSION
 
 LABEL name="Apache Solr" \
   maintainer="i2 Group" \
@@ -107,12 +149,16 @@ RUN set -ex; \
   groupadd -r --gid "$SOLR_GID" "$SOLR_GROUP"; \
   useradd -r --uid "$SOLR_UID" --gid "$SOLR_GID" "$SOLR_USER"
 
+# Copy extracted Solr from the downloader-and-unpacker stage
+COPY --from=downloader-and-unpacker /opt/solr-${SOLR_VERSION} /opt/solr-${SOLR_VERSION}
+
 # add symlink to /opt/solr, remove what we don't want.
 # Remove the Dockerfile because it might not represent the dockerfile that was used to generate the image.
 RUN set -ex; \
   (cd /opt; ln -s solr-*/ solr); \
   rm -Rf /opt/solr/docs /opt/solr/docker/Dockerfile;
 
+# Code from official image's Dockerfile...
 RUN set -ex; \
   mkdir -p /opt/solr/server/solr/lib /docker-entrypoint-initdb.d; \
   cp /opt/solr/bin/solr.in.sh /etc/default/solr.in.sh; \
@@ -128,15 +174,14 @@ RUN set -ex; \
 COPY --chown=0:0 "docker-entrypoint.sh" "/opt/solr/docker-entrypoint.sh"
 COPY --chown=0:0 "environment.sh" "/opt/solr/environment.sh"
 
+# Copy jattach from the downloader-and-unpacker stage
+COPY --from=downloader-and-unpacker /jattach/jattach /usr/local/bin/jattach
+
 # Gosu is part of the base image so we don't try to reinstall
 # Netcat is ncat which is part of nmap package
-# jattach needs to be manually downloaded
 RUN set -ex; \
-    cd /usr/local/bin; wget -nv https://github.com/jattach/jattach/releases/download/v2.2/jattach; chmod 755 jattach; \
-    echo >jattach.sha512 "53a5d9b49875bc4437ac5b20440e48c66fa42df4aa42c3e50b03a3e5937a855a071a4e65c53b304a47c11353f817feac47ef6d7d86bd9641dc11d2e7d0af6a7a  jattach"; \
-    sha512sum -c jattach.sha512; rm jattach.sha512; \
-    microdnf update; \
-    microdnf -y --setopt=install_weak_deps=0 install acl lsof procps wget nmap; \
+    microdnf -y update; \
+    microdnf -y --setopt=install_weak_deps=0 install acl lsof procps nmap; \
     microdnf clean all;
 
 VOLUME /var/solr
diff --git a/images/zookeeper/3.9/Dockerfile b/images/zookeeper/3.9/Dockerfile
--- a/images/zookeeper/3.9/Dockerfile
+++ b/images/zookeeper/3.9/Dockerfile
@@ -11,14 +11,80 @@ ARG revision
 ARG version
 
 # Inspired by: https://github.com/31z4/zookeeper-docker
+# but then re-arranged to multi-stage build and UBI base image
 ARG ZK_VERSION="3.9.4"
+ARG GPG_KEY=3F7A1D16FA4217B1DC75E1C9FFE35B7F15DFA1BA
 
+
+
+# Stage 1: Download everything we need
+# Use ubuntu, because we can't untar on ubi reliably on arm64.
+# (on arm64, tar reports a lot of "Cannot open: Invalid argument" errors)
+FROM ubuntu:24.04 as downloader-and-unpacker
+
+# Bring global-scope args into the build stage, and add more
+ARG GPG_KEY
+ARG ZK_VERSION
+ARG SHORT_DISTRO_NAME=zookeeper-${ZK_VERSION}
+ARG DISTRO_NAME=apache-zookeeper-${ZK_VERSION}-bin
+
+# Dependencies for downloading and verifying Zookeeper.
+# Subset of those used in the official Zookeeper image.
+RUN apt-get update && \
+    apt-get install --no-install-recommends -y \
+      ca-certificates \
+      dirmngr \
+      gnupg \
+      wget \
+    && \
+    rm -rf /var/lib/apt/lists/*
+
+# Download Apache Zookeeper, verify its PGP signature, untar and clean up
+# Code from official image's Dockerfile...
+# ... truncated after the 'tar' step
+# ... with wget told --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --retry-connrefused for robustness.
+RUN set -eux; \
+    ddist() { \
+        local f="$1"; shift; \
+        local distFile="$1"; shift; \
+        local success=; \
+        local distUrl=; \
+        for distUrl in \
+            'https://www.apache.org/dyn/closer.cgi?action=download&filename=' \
+            https://www-us.apache.org/dist/ \
+            https://www.apache.org/dist/ \
+            https://archive.apache.org/dist/ \
+        ; do \
+            if wget --progress=dot:mega --tries=3 --timeout=10 --waitretry=10 --retry-connrefused -O "$f" "$distUrl$distFile" && [ -s "$f" ]; then \
+                success=1; \
+                break; \
+            fi; \
+        done; \
+        [ -n "$success" ]; \
+    }; \
+    ddist "$DISTRO_NAME.tar.gz" "zookeeper/$SHORT_DISTRO_NAME/$DISTRO_NAME.tar.gz"; \
+    ddist "$DISTRO_NAME.tar.gz.asc" "zookeeper/$SHORT_DISTRO_NAME/$DISTRO_NAME.tar.gz.asc"; \
+    export GNUPGHOME="$(mktemp -d)"; \
+    gpg --keyserver hkps://keyserver.pgp.com --recv-key "$GPG_KEY" || \
+    gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys "$GPG_KEY" || \
+    gpg --keyserver hkps://pgp.mit.edu --recv-keys "$GPG_KEY"; \
+    gpg --batch --verify "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz"; \
+    tar -zxf "$DISTRO_NAME.tar.gz"; \
+    rm -rf "$GNUPGHOME" "$DISTRO_NAME.tar.gz" "$DISTRO_NAME.tar.gz.asc"; \
+    ls -al "/$DISTRO_NAME"
+
+
+
+# Stage 2: Create the final image
 FROM i2group/i2eng-analyze-containers-base:ubi-jdk17-${revision}
 
-# Bring global-scope args into the build stage
+# Bring global-scope args into the build stage, and add more
 ARG revision
 ARG version
 ARG ZK_VERSION
+ARG DISTRO_NAME=apache-zookeeper-${ZK_VERSION}-bin
+
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
 LABEL name="Apache ZooKeeper" \
   maintainer="i2 Group" \
@@ -30,6 +96,7 @@ LABEL name="Apache ZooKeeper" \
   and naming registry for large distributed systems." \
   license="MIT"
 
+# Code from official image's Dockerfile...
 ENV JAVA_HOME="/opt/java/openjdk" \
     PATH="/opt/java/openjdk/bin:$PATH" \
     ZOO_CONF_DIR=/conf \
@@ -45,63 +112,34 @@ ENV JAVA_HOME="/opt/java/openjdk" \
     ZOO_STANDALONE_ENABLED=true \
     ZOO_ADMINSERVER_ENABLED=true
 
-# Add a user with an explicit UID/GID and create necessary directories
+# nmap package is required to supply cli netcat (command nc), this is required
+# for zookeeper status checking.
 RUN set -eux; \
-    groupadd -r zookeeper --gid=1000; \
-    useradd -r -g zookeeper --uid=1000 zookeeper; \
-    mkdir -p "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR" "$ZOO_LOG_DIR"; \
-    chown zookeeper:zookeeper "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR" "$ZOO_LOG_DIR"
-
-# Gosu is part of the base image so we don't try to reinstall
-# Netcat is ncat which is part of nmap package
-# Install required packages
-RUN set -eux; \
-    microdnf -y update; \
-    microdnf install -y --setopt=install_weak_deps=0 \
-        ca-certificates \
-        dirmngr \
-        gnupg \
-        nmap \
-        wget; \
+    microdnf -y update && \
+    microdnf -y install --setopt=install_weak_deps=0 \
+      nmap \
+    && \
     microdnf clean all;
 
-ARG GPG_KEY=3F7A1D16FA4217B1DC75E1C9FFE35B7F15DFA1BA
-ARG SHORT_DISTRO_NAME=zookeeper-${ZK_VERSION}
-ARG DISTRO_NAME=apache-zookeeper-${ZK_VERSION}-bin
-
-# Download Apache Zookeeper, verify its PGP signature, untar and clean up
+# Add a user with an explicit UID/GID and create necessary directories
+# Install shadow-utils temporarily, use it, then remove it to keep image small
 RUN set -eux; \
-    ddist() { \
-        local f="$1"; shift; \
-        local distFile="$1"; shift; \
-        local success=; \
-        local distUrl=; \
-        for distUrl in \
-            'https://www.apache.org/dyn/closer.cgi?action=download&filename=' \
-            https://www-us.apache.org/dist/ \
-            https://www.apache.org/dist/ \
-            https://archive.apache.org/dist/ \
-        ; do \
-            if wget -q -O "$f" "$distUrl$distFile" && [ -s "$f" ]; then \
-                success=1; \
-                break; \
-            fi; \
-        done; \
-        [ -n "$success" ]; \
-    }; \
-    ddist "$DISTRO_NAME.tar.gz" "zookeeper/$SHORT_DISTRO_NAME/$DISTRO_NAME.tar.gz"; \
-    ddist "$DISTRO_NAME.tar.gz.asc" "zookeeper/$SHORT_DISTRO_NAME/$DISTRO_NAME.tar.gz.asc"; \
-    export GNUPGHOME="$(mktemp -d)"; \
-    gpg --keyserver hkps://keyserver.pgp.com --recv-key "$GPG_KEY" || \
-    gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys "$GPG_KEY" || \
-    gpg --keyserver hkps://pgp.mit.edu --recv-keys "$GPG_KEY"; \
-    gpg --batch --verify "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz"; \
-    tar -zxf "$DISTRO_NAME.tar.gz"; \
+    microdnf -y install shadow-utils && \
+    groupadd -r zookeeper --gid=1000 && \
+    useradd -r -g zookeeper --uid=1000 zookeeper && \
+    mkdir -p "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR" "$ZOO_LOG_DIR" && \
+    chown zookeeper:zookeeper "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR" "$ZOO_LOG_DIR" && \
+    microdnf -y remove shadow-utils && \
+    microdnf clean all
+
+# Copy Apache Zookeeper from the downloader-and-unpacker stage
+COPY --from=downloader-and-unpacker --chown=zookeeper:zookeeper "/$DISTRO_NAME" "/$DISTRO_NAME"
+
+# Code from official image's Dockerfile that didn't go into the downloader stage
+RUN \
     mv "$DISTRO_NAME/conf/"* "$ZOO_CONF_DIR"; \
-    rm -rf "$GNUPGHOME" "$DISTRO_NAME.tar.gz" "$DISTRO_NAME.tar.gz.asc"; \
-    chown -R zookeeper:zookeeper "/$DISTRO_NAME"; \
-    # Add symlink for easier access in SaaS
-    ln -s "/$DISTRO_NAME" /apache-zookeeper-bin;
+    ln -s "/$DISTRO_NAME" /apache-zookeeper-bin \
+    && ls -al /
 
 WORKDIR $DISTRO_NAME
 VOLUME ["$ZOO_DATA_DIR", "$ZOO_DATA_LOG_DIR", "$ZOO_LOG_DIR"]
